"use client";
import { useState } from "react";
import { useResource } from "@/hooks/useResource";
import { api } from "@/services/api";
import PageHeading from "@/components/PageHeading";
import ResourceState from "@/components/ResourceState";
type Field = { id: string; label: string; type: string; optional?: boolean; disabled?: boolean; options?: string[]; help?: string; placeholder?: string; min?: number; max?: number; minLength?: number; maxLength?: number; maxFiles?: number; maxFileSize?: number; visibility?: string; when?: { id: string; value: string | boolean | number; operator?: string } };
type Form = { _id?: string; key: string; name: string; context: string; category: string; active: boolean; version?: number; fields: Field[] };
const empty: Form = { key: "", name: "", context: "CREATOR_ONBOARDING", category: "", active: true, fields: [] };
const types = ["text", "textarea", "number", "email", "tel", "url", "date", "time", "datetime-local", "date_range", "time_range", "select", "multiselect", "radio", "checkbox", "boolean", "file", "files", "image", "images", "video", "raw", "address", "location", "price", "currency", "section", "information", "service"];
export default function FormBuilder() {
  const r = useResource<Form[]>("/admin/configuration/forms"), categories = useResource<{ title: string }[]>("/services");
  const [form, setForm] = useState<Form>(), [error, setError] = useState(""), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  function field(index: number, patch: Partial<Field>) { setForm(f => f && ({ ...f, fields: f.fields.map((x, i) => i === index ? { ...x, ...patch } : x) })); }
  return <><PageHeading title="Dynamic forms" description="Manage service-specific questions, validation, visibility and conditional fields without changing code." action={<button className="btn" onClick={() => { setForm({ ...empty }); setError(""); }}>Create form</button>} /><ResourceState {...r} />{message && <p role="status">{message}</p>}
    <div className="grid gap-3 mb-8 md:grid-cols-3">{r.data?.map(f => <button key={f._id} className="panel text-left" onClick={() => { setForm(structuredClone(f)); setError(""); }}><b>{f.name}</b><p className="muted text-xs mt-2">{f.context} · {f.category || "All categories"}</p><span className="badge">V{f.version} · {f.active ? "Active" : "Archived"} · {f.fields.length} fields</span></button>)}</div>
    {form && <form className="panel space-y-5" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(""); try { await api(`/admin/configuration/forms${form._id ? `/${form._id}` : ""}`, { method: form._id ? "PUT" : "POST", body: JSON.stringify(form) }); setMessage("Form saved. New submissions use this version immediately."); setForm(undefined); await r.reload(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save."); } finally { setBusy(false); } }}>
      <h2 className="display text-3xl">{form._id ? "Edit form" : "New form"}</h2><div className="grid gap-4 sm:grid-cols-2"><label className="field">Name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label className="field">Stable key<input required pattern="[a-z0-9_-]+" value={form.key} onChange={e => setForm({ ...form, key: e.target.value })} /></label><label className="field">Used for<select value={form.context} onChange={e => setForm({ ...form, context: e.target.value })}>{["CUSTOMER_REGISTRATION", "CREATOR_ONBOARDING", "REQUIREMENT_FORM", "DIRECT_BOOKING", "PROPOSAL_FORM", "SERVICE_COMPLETION"].map(c => <option key={c}>{c}</option>)}</select></label><label className="field">Category<select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}><option value="">All categories</option>{categories.data?.map(c => <option key={c.title}>{c.title}</option>)}</select></label></div><label className="flex gap-3 text-sm"><input type="checkbox" checked={form.active} onChange={e => setForm({ ...form, active: e.target.checked })} />Active</label>
      {form.fields.map((f, i) => <fieldset className="rounded-lg border border-stone-200 p-5 space-y-4" key={i}><legend className="text-sm font-semibold">{i + 1}. {f.label || "New question"}</legend><div className="grid gap-4 sm:grid-cols-3"><label className="field">Field key<input required pattern="[a-zA-Z][a-zA-Z0-9_]*" value={f.id} onChange={e => field(i, { id: e.target.value })} /></label><label className="field">Label<input required value={f.label} onChange={e => field(i, { label: e.target.value })} /></label><label className="field">Type<select value={f.type} onChange={e => field(i, { type: e.target.value })}>{types.map(t => <option key={t}>{t}</option>)}</select></label></div><div className="flex gap-5 text-sm"><label><input type="checkbox" checked={!f.optional} onChange={e => field(i, { optional: !e.target.checked })} /> Required</label><label><input type="checkbox" checked={!!f.disabled} onChange={e => field(i, { disabled: e.target.checked })} /> Disabled</label></div>
        {["select", "multiselect", "radio"].includes(f.type) && <label className="field">Options (one per line)<textarea value={f.options?.join("\n") || ""} onChange={e => field(i, { options: e.target.value.split("\n").filter(Boolean) })} /></label>}
        <div className="grid gap-4 sm:grid-cols-2"><label className="field">Help text<input value={f.help || ""} onChange={e => field(i, { help: e.target.value })} /></label><label className="field">Visibility<select value={f.visibility || "ADMIN_AND_CREATOR"} onChange={e => field(i, { visibility: e.target.value })}>{["PUBLIC", "CUSTOMER", "CREATOR", "ADMIN", "ADMIN_AND_CREATOR", "BOOKED_PARTIES"].map(v => <option key={v}>{v}</option>)}</select></label></div>
        <details><summary className="cursor-pointer text-sm text-brand">Validation and conditional display</summary><div className="grid gap-3 mt-4 sm:grid-cols-3">{(["min", "max", "minLength", "maxLength", "maxFiles", "maxFileSize"] as const).map(k => <label className="field" key={k}>{k}<input type="number" value={f[k] ?? ""} onChange={e => field(i, { [k]: e.target.value ? Number(e.target.value) : undefined })} /></label>)}</div><div className="grid gap-3 mt-4 sm:grid-cols-3"><label className="field">Show when field<select value={f.when?.id || ""} onChange={e => field(i, { when: e.target.value ? { id: e.target.value, value: "", operator: "equals" } : undefined })}><option value="">Always show</option>{form.fields.filter(x => x.id && x.id !== f.id).map(x => <option key={x.id} value={x.id}>{x.label}</option>)}</select></label>{f.when && <><label className="field">Operator<select value={f.when.operator || "equals"} onChange={e => field(i, { when: { ...f.when!, operator: e.target.value } })}>{["equals", "notEquals", "contains", "in"].map(o => <option key={o}>{o}</option>)}</select></label><label className="field">Value<input value={String(f.when.value)} onChange={e => field(i, { when: { ...f.when!, value: e.target.value } })} /></label></>}</div></details>
        <div className="flex gap-4 text-xs"><button type="button" disabled={i === 0} onClick={() => { const fields = [...form.fields]; [fields[i - 1], fields[i]] = [fields[i], fields[i - 1]]; setForm({ ...form, fields }); }}>Move up</button><button type="button" disabled={i === form.fields.length - 1} onClick={() => { const fields = [...form.fields]; [fields[i + 1], fields[i]] = [fields[i], fields[i + 1]]; setForm({ ...form, fields }); }}>Move down</button><button type="button" className="text-red-700" onClick={() => setForm({ ...form, fields: form.fields.filter((_, j) => j !== i) })}>Delete field</button></div>
      </fieldset>)}<button className="btn btn-outline" type="button" onClick={() => setForm({ ...form, fields: [...form.fields, { id: "", label: "", type: "text", optional: true }] })}>Add question</button>{error && <p role="alert" className="error-box">{error}</p>}<div className="flex gap-3"><button className="btn" disabled={busy}>{busy ? "Saving…" : "Save form"}</button><button type="button" className="btn btn-outline" onClick={() => setForm(undefined)}>Close</button></div>
    </form>}
  </>;
}
