"use client";
import { useState } from "react";
import { api, money } from "@/services/api";
import { useResource } from "@/hooks/useResource";
import PageHeading from "@/components/PageHeading";
import ResourceState from "@/components/ResourceState";
type RecordItem = { _id: string; title?: string; businessName?: string; ownerName?: string; status?: string; applicationStatus?: string; event?: string; service?: string; category?: string; city?: string; date?: string; startTime?: string; endTime?: string; description?: string; instructions?: string; reason?: string; explanation?: string; decision?: string; resolution?: string; reviewReason?: string; amount?: number; commissionRate?: number; commissionAmount?: number; paymentStatus?: string; price?: number; budgetMin?: number; budgetMax?: number; user?: string; gallery?: string[]; verificationFiles?: string[]; attachments?: string[]; files?: string[]; application?: Record<string, unknown>; history?: Record<string, unknown>[]; reviewHistory?: Record<string, unknown>[]; action?: string; entityType?: string; entityId?: string; createdAt?: string; message?: string; inclusions?: string; context?: string; services?: string[] };
const paths: Record<string, string> = { bookings: "/bookings", requirements: "/requirements", proposals: "/proposals", applications: "/admin/marketplace/applications", appeals: "/appeals", disputes: "/disputes", messages: "/conversations", audit: "/admin/configuration/audit" };
export default function Records({ resource }: { resource: string }) {
  const r = useResource<RecordItem[]>(paths[resource]); const [loadError, setLoadError] = useState(""); const [selected, setSelected] = useState<RecordItem>(), [search, setSearch] = useState(""), [filter, setFilter] = useState("");
  const rows = (r.data || []).filter(x => (!filter || (x.applicationStatus || x.status) === filter) && `${x.title || x.businessName || x.action || ""} ${x.city || ""} ${x.category || x.service || ""}`.toLowerCase().includes(search.toLowerCase()));
  return <><PageHeading title={resource === "applications" ? "Creator verification" : resource === "audit" ? "Audit history" : resource[0].toUpperCase() + resource.slice(1)} description={resource === "bookings" ? "Approve requests before creators see them. Record demo payment confirmation and manage the booking lifecycle." : resource === "requirements" ? "Review and publish customer requirements before creators receive opportunities." : "Review platform activity and keep every decision traceable."} /><ResourceState {...r} />{loadError && <p role="alert" className="error-box">{loadError}</p>}
    <div className="panel mb-6"><div className="flex flex-wrap gap-3 mb-5"><input className="input max-w-sm" aria-label="Search records" placeholder="Search title, city or category" value={search} onChange={e => setSearch(e.target.value)} /><select className="input max-w-xs" aria-label="Filter status" value={filter} onChange={e => setFilter(e.target.value)}><option value="">All statuses</option>{[...new Set((r.data || []).map(x => x.applicationStatus || x.status).filter(Boolean))].map(s => <option key={s}>{s}</option>)}</select></div><div className="overflow-x-auto"><table><thead><tr><th>Record</th><th>Details</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(x => <tr key={x._id}><td><b>{x.title || x.businessName || x.action || x.reason || "Proposal"}</b><p className="muted text-xs">{x._id}</p></td><td>{[x.city, x.date, x.category || x.service || x.entityType].filter(Boolean).join(" · ")}{(x.amount || x.price) && <p>{money(x.amount || x.price || 0)}</p>}</td><td><span className="badge">{x.applicationStatus || x.status || x.context || "Recorded"}</span></td><td><button className="text-brand" onClick={async () => { setLoadError(""); try { setSelected(["bookings", "requirements"].includes(resource) ? await api<RecordItem>(`/${resource}/${x._id}`) : x); } catch (e) { setLoadError(e instanceof Error ? e.message : "Unable to load record."); } }}>Review</button></td></tr>)}</tbody></table></div>{!rows.length && !r.loading && <p className="muted py-6">No records match these filters.</p>}</div>
    {selected && <div className="panel"><div className="flex justify-between gap-4 mb-5"><h2 className="display text-3xl">{selected.title || selected.businessName || "Record details"}</h2><button onClick={() => setSelected(undefined)} aria-label="Close details">×</button></div><RecordDetail key={selected._id} resource={resource} row={selected} onSaved={async () => { setSelected(undefined); await r.reload(); }} /></div>}
  </>;
}
function RecordDetail({ resource, row, onSaved }: { resource: string; row: RecordItem; onSaved: () => Promise<void> }) {
  const [reason, setReason] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false), [mode, setMode] = useState("PUBLIC_TO_MATCHING_CREATORS"), [invited, setInvited] = useState("");
  const status = row.applicationStatus || row.status || "";
  async function act(action: string) { setBusy(true); setError(""); try {
    const path = resource === "bookings" ? `/bookings/${row._id}/actions` : resource === "applications" ? `/admin/marketplace/applications/${row._id}/review` : `/${resource}/${row._id}/review`;
    await api(path, { method: "POST", body: JSON.stringify(["appeals", "disputes"].includes(resource) ? { status: action, reason } : resource === "requirements" ? { action, reason, publishingMode: mode, invited: invited.split(/[\s,]+/).filter(Boolean) } : { action, reason }) }); await onSaved();
  } catch (e) { setError(e instanceof Error ? e.message : "Unable to update."); } finally { setBusy(false); } }
  const actions = resource === "bookings" ? ["PENDING_ADMIN_REVIEW", "NEEDS_INFORMATION"].includes(status) ? [["approve", "Approve & send to creator"], ["reject", "Reject"], ["information", "Request information"]] : ["AWAITING_CLIENT_CONFIRMATION", "AWAITING_PAYMENT"].includes(status) ? [["paid", "Record demo payment as paid"]] : status === "REFUND_PENDING" ? [["refund", "Record demo refund"]] : [] : resource === "requirements" ? [["approve", "Approve & publish"], ["reject", "Reject"], ["information", "Request information"]] : resource === "applications" ? [["approve", "Approve creator"], ["reject", "Reject application"], ["information", "Request information"], ["suspend", "Suspend"], ["reactivate", "Reactivate"]] : ["appeals", "disputes"].includes(resource) ? [["UNDER_REVIEW", "Under review"], ["MORE_INFO_REQUIRED", "Request evidence"], ["APPROVED", "Approve"], ["REJECTED", "Reject"], ["CLOSED", "Close"]] : [];
  return <div className="space-y-5"><dl className="grid gap-4 sm:grid-cols-2">{Object.entries(row).filter(([key, value]) => !["_id", "__v", "user", "createdAt", "updatedAt"].includes(key) && ["string", "number", "boolean"].includes(typeof value)).map(([key, value]) => <div key={key}><dt className="text-xs font-semibold capitalize">{key.replace(/([A-Z])/g, " $1")}</dt><dd className="muted whitespace-pre-wrap text-sm break-words">{String(value)}</dd></div>)}</dl>
    {row.application && <details><summary className="cursor-pointer font-semibold">Application answers</summary><dl className="space-y-3 mt-4">{Object.entries(row.application).filter(([k]) => !["idCard", "folder", "profileImage", "workSamples"].includes(k)).map(([key, value]) => <div key={key}><dt className="text-xs font-semibold">{key}</dt><dd className="text-sm muted whitespace-pre-wrap">{Array.isArray(value) ? value.join(", ") : String(value)}</dd></div>)}</dl></details>}
    {row.gallery && <div className="grid grid-cols-3 sm:grid-cols-5 gap-3">{row.gallery.map((url, i) => <a href={url} key={`${url}-${i}`} target="_blank" rel="noreferrer"><img src={url} alt={`Portfolio ${i + 1}`} className="h-24 w-full object-cover rounded" /></a>)}</div>}
    {resource === "applications" && row.user && <VerificationFiles user={row.user} creator={row._id} />}
    {[...(row.files || []), ...(row.attachments || [])].map(id => <PrivateFile key={id} id={id} />)}
    {(row.history || row.reviewHistory) && <details><summary className="cursor-pointer font-semibold">Decision history</summary>{(row.history || row.reviewHistory)?.map((h, i) => <p className="text-sm muted border-b py-3" key={i}>{Object.entries(h).filter(([k]) => ["status", "reason", "at", "note"].includes(k)).map(([, v]) => String(v)).join(" · ")}</p>)}</details>}
    {resource === "messages" && <ModerationThread id={row._id} />}
    {resource === "requirements" && <><label className="field">Publication mode<select value={mode} onChange={e => setMode(e.target.value)}>{["PUBLIC_TO_MATCHING_CREATORS", "PRIVATE_INVITATION", "BOTH"].map(m => <option key={m}>{m}</option>)}</select></label><label className="field">Invite creator IDs (optional, comma separated)<textarea value={invited} onChange={e => setInvited(e.target.value)} /></label></>}
    {["bookings", "requirements"].includes(resource) && ["PENDING_ADMIN_REVIEW", "NEEDS_INFORMATION", "REJECTED"].includes(status) && <details><summary className="text-brand text-sm cursor-pointer">Edit request details before approval</summary><form className="space-y-3 mt-4" onSubmit={async e => { e.preventDefault(); setError(""); setBusy(true); try { const text = new FormData(e.currentTarget).get("text"); await api(`/${resource}/${row._id}/details`, { method: "PATCH", body: JSON.stringify(resource === "bookings" ? { instructions: text } : { description: text }) }); await onSaved(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update."); } finally { setBusy(false); } }}><label className="field">Updated requirements<textarea name="text" required minLength={20} defaultValue={resource === "bookings" ? row.instructions : row.description} /></label><button className="btn" disabled={busy}>Save changes</button></form></details>}
    {!!actions.length && <><label className="field">Decision reason / information needed<textarea value={reason} onChange={e => setReason(e.target.value)} maxLength={3000} /></label><div className="flex flex-wrap gap-3">{actions.map(([action, label]) => <button className="btn btn-outline" disabled={busy} key={action} onClick={() => act(action)}>{label}</button>)}</div></>}{error && <p role="alert" className="error-box">{error}</p>}
  </div>;
}
function PrivateFile({ id, label = "Open private file", path }: { id: string; label?: string; path?: string }) { const [url, setUrl] = useState(""), [error, setError] = useState(""); return <div className="text-sm">{url ? <a href={url} className="text-brand underline" target="_blank" rel="noopener noreferrer">{label} (expires in 5 minutes)</a> : <button className="text-brand underline" onClick={async () => { try { setUrl((await api<{ url: string }>(path || `/assets/${id}/access`)).url); } catch (e) { setError(e instanceof Error ? e.message : "Cannot open file."); } }}>{label}</button>}{error && <p role="alert">{error}</p>}</div>; }
function VerificationFiles({ user, creator }: { user: string; creator: string }) { const r = useResource<{ _id: string; originalFilename: string; purpose: string; size: number }[]>(`/assets?owner=${user}`); return <section className="space-y-3"><h3 className="font-semibold">Private verification evidence</h3><ResourceState {...r} /><PrivateFile id={creator} path={`/admin/creator/${creator}/identity`} label="Open identity card" />{r.data?.filter(a => a.purpose === "verification").map(a => <PrivateFile id={a._id} label={`${a.originalFilename} (${Math.round(a.size / 1024)} KB)`} key={a._id} />)}</section>; }
function ModerationThread({ id }: { id: string }) { const r = useResource<{ _id: string; text: string; original?: string; createdAt: string; moderated: boolean }[]>(`/conversations/${id}/messages`); const [error, setError] = useState(""); return <div className="space-y-4"><ResourceState {...r} />{r.data?.map(m => <article key={m._id} className="border rounded p-4"><p>{m.text}</p>{m.moderated && <details><summary>Original (admin only)</summary><p>{m.original}</p></details>}<p className="muted text-xs">{new Date(m.createdAt).toLocaleString()}</p></article>)}<form onSubmit={async e => { e.preventDefault(); const f = e.currentTarget; try { await api(`/conversations/${id}/messages`, { method: "POST", body: JSON.stringify({ text: new FormData(f).get("text") }) }); f.reset(); await r.reload(); } catch (e) { setError(e instanceof Error ? e.message : "Message failed."); } }}><label className="field">Reply as Memooria<textarea name="text" required /></label><button className="btn mt-3">Send reply</button>{error && <p role="alert">{error}</p>}</form></div>; }
